config/routes.rb
Rails.application.routes.draw do
 get 'map', to: 'map#index', as: 'custom_map'

  
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/geojson_builder.rb
class GeojsonBuilder < ApplicationRecord
    validates :lat, presence: true
    validates :lng, presence: true
    validates :state, presence: true
    validates :population, presence: true
    validates :abbreviation, presence: true

    def build_point(point, geojson)
        geojson << {
            type: "Feature",
            geometry: {
                type: "Point",
                coordinates: [
                    point.lng,
                    point.lat
                ],
            }
            properties: {
                state: point.name,
                population: point.population,
                abbreviation: point.abbreviation,
                marker-symbol: 'circle',
                marker-color: "",
                marker-size: "medium"

            }
        }
        
    end
end

app/models/map.rb
class Map < ApplicationRecord
  validates :lat, presence: true
  validates :lng, presence: true
  validates :state, presence: true
  validates :population, presence: true
  validates :abbreviation, presence: true

  def build_geojson
    {
        type: "Feature",
        geometry: {
            type: "Point",
            coordinates: [
            lng,
            lat
            ]
        },
        properties: {
            id: id,
            state: state,
            population: population,
            abbreviation: abbreviation
        }
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @maps = Map.all.map 
    @geojson = Array.new
    build_geojson(@maps, @geojson)

    respond_to do |format|
      format.html
      format.json { render json: @geojson}
    end
  end

  def build_geojson(points, geojson)
    points.each do | point |
      geojson << GeojsonBuilder.build_point(point)
    end
  end


  private
  def json_response(object, status = :ok)
    render json: object, status: status
  end

end
 

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_helper.rb
module CarHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/application/_footer.html.haml
.grid-x.full.footer.align-center.align-middle
    .cell.small-2.sponsor.mml.mmr
        %img{ src:'http://www.norrislakemarinas.org/wp-content/themes/norris/img/logo_placeholder.png' }
    .cell.small-2.copyrights.lml.lmr
        %p.mpt.text-center IceCreamArchitecture © 2019
    .cell.small-2.social-media.mml.mmr
        %a{ href:'https://twitter.com' }
            %i.fa.fa-twitter-square.spl.spr
        %a{ href:'https://youtube.com' }
            %i.fa.fa-youtube-square.spl.spr
        %a{ href:'https://instragram.com' }
            %i.fa.fa-instagram.spl.spr

app/views/application/_header.html.haml
.title-bar{"data-hide-for" => "medium", "data-responsive-toggle" => "example-menu"}
  %button.menu-icon{"data-toggle" => "", :type => "button"}
  .title-bar-title.mpl.mpr Mapita
#example-menu.top-bar
  .top-bar-left
    %ul.no-bullet
      %li.menu-text.lpl.lpr Mapita
      %li.lpl.lpr
        = link_to root_path do 
          Home
      %li.lpl.lpr
        = link_to custom_map_path do 
          Map
      %li.lpl.lpr
        %a Contact
  .top-bar-right
    %ul.menu
      %li
        %input{:placeholder => "Search", :type => "search"}/
      %li
        %button.button{:type => "button"} Search

app/views/layouts/application.html.haml
!!!
%html
  %head

    %meta{ name: 'viewport', content: 'width=device-width, initial-scale=1, shrink-to-fit=no' }


    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MapboxApp
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag 'https://api.mapbox.com/mapbox-gl-js/v1.4.1/mapbox-gl.css'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    
  %body

    = render'header'

    = yield

    = render'footer'

app/views/map/index.html.haml
.card.grid-x
    .card-divider.cell
        .h4 Find Map of Mexico with population and abbreviations for each state
    .card-section.cell.flex-container.align-center
        #custom-map

app/views/pages/index.html.haml
.card.grid-x
    .card-divider.cell
        .h4 Zoom into your favourite street
    .card-section.cell.flex-container.align-center
        #map